### ISSUE TITLE
Improve build step on Linux

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGL/GLFW.jl#30]
I've wanted to improve the build of GLFW, but I never got around to it and I still am not too motivated.
I open at least an issue, and describe what needs to be done for now.
On Unix, you need to have at least cmake installed. Is there an easy way to do this automatically?
On Ubuntu, I additionally need  `xorg-dev` and `libglu1-mesa-dev`. We should be able to get them via BinDeps?!
Windows seems to be fine the way it is.
I don't know about any other operating systems.

Best,
Simon

**Comment by jayschwa** [comment]
I feel like the ideal way would be:
1. If the system already has a new-ish version, use that.
2. If it doesn't have a new-ish version, use the system package manager to get one.
3. If none of the above works, try to build it.

The problem with (2) is that many system package repos seem to lag behind quite a bit. For example, GLFW 3 has been out for ~18 months, and it looks like Debian and Ubuntu have only now picked it up in their latest releases. The fact that it seems to have different names in across package managers can make things tricky too.

The problem with (3) is that you need some dependencies installed for the build to work. Chances are if (2) failed for some reason, (3) probably isn't going to work for the dependencies either.

I like the idea of BinDeps, but I didn't have much luck with it and found it confusing the last time I tried to use it.

In general, I feel like trying to make it work for every platform and package manager is a lost cause and time that would be better spent elsewhere. For some time, I've contemplated just changing the install process to detect if the library exists in the system path or not, and printing a message to the GLFW download page if the latter. Essentially, be up front with the user about making them install it rather than failing with some cryptic build error message.

**Comment by SimonDanisch** [comment]
We can definitely improve on the error message, which is probably the first step we can do!
I'd add 4. give good error messages if build fails. From my experience, installing cmake and getting the dependencies is enough to get the build working.
`I like the idea of BinDeps, but I didn't have much luck with it and found it confusing the last time I tried to use it.`
Haha, that was exactly what happened to me. Just looked into it today, hoping it got less confusing, but I just decided to open this issue instead.

**Comment by SimonDanisch** [comment]
So I think on Ubuntu, the hardest part is to get the deps, which we could manually do via the commandline (which is what BinDeps does in the end anyways, right)? Basically try what package managers are available and then use them.
I'm not very accustomed to Mac Os so I wouldn't really know what needs to be done there. I just know, that it was a little bit painful to install cmake for the command-line, the one time I tried.

**Comment by KajWiik** [comment]
Perhaps a mention in the README.md that cmake is a dependency would be good... Rather difficult to find out what's the real problem...

**Comment by SimonDanisch** [comment]
That's a good point, not sure why we still don't have that in the README. Care to make an edit to the readme? You can just edit it directly in github: https://github.com/JuliaGL/GLFW.jl/blob/master/README.md
